version: '3.7'

services:
  service-discovery:
    container_name: ${SERVICE_DISCOVERY_APPLICATION_NAME}
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: ${JAVA_VERSION}
        SERVICE_DISCOVERY_PORT: ${SERVICE_DISCOVERY_PORT}
    environment:
      - JAVA_VERSION=${JAVA_VERSION}
      - SERVICE_DISCOVERY_APPLICATION_NAME=${SERVICE_DISCOVERY_APPLICATION_NAME}
      - SERVICE_DISCOVERY_HOST=${SERVICE_DISCOVERY_HOST}
      - SERVICE_DISCOVERY_PORT=${SERVICE_DISCOVERY_PORT}
    restart: on-failure
    ports:
      - ${SERVICE_DISCOVERY_PORT}:${SERVICE_DISCOVERY_PORT}

  api-gateway-service:
    container_name: ${API_GATEWAY_SERVICE_APPLICATION_NAME}
    build:
      context: ./api-gateway-service
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: ${JAVA_VERSION}
        API_GATEWAY_SERVICE_PORT: ${API_GATEWAY_SERVICE_PORT}
    environment:
      - JAVA_VERSION=${JAVA_VERSION}
      - API_GATEWAY_SERVICE_APPLICATION_NAME=${API_GATEWAY_SERVICE_APPLICATION_NAME}
      - API_GATEWAY_SERVICE_HOST=${API_GATEWAY_SERVICE_HOST}
      - API_GATEWAY_SERVICE_PORT=${API_GATEWAY_SERVICE_PORT}
      - SERVICE_DISCOVERY_HOST=${SERVICE_DISCOVERY_HOST}
      - SERVICE_DISCOVERY_PORT=${SERVICE_DISCOVERY_PORT}
    restart: on-failure
    depends_on:
      - service-discovery
    ports:
      - ${API_GATEWAY_SERVICE_PORT}:${API_GATEWAY_SERVICE_PORT}
