spring:
  application:
    name: ${TRANSACTION_SERVICE_APPLICATION_NAME}

  kafka:
    bootstrap-servers: ${KAFKA1_SERVER_HOST}:${KAFKA1_SERVER_PORT_INNER},${KAFKA2_SERVER_HOST}:${KAFKA2_SERVER_PORT_INNER}
    listener:
      ack-mode: record
    consumer:
      auto-offset-reset: earliest
      group-id: transaction-service-group-id
    topic:
      transaction:
        name: ${TRANSACTION_SERVICE_KAFKA_TOPIC_TRANSACTION_NAME}
    streams:
      replication-factor: ${KAFKA_SERVER_REPLICATION_FACTOR}

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST}:${SERVICE_DISCOVERY_PORT}/eureka
    register-with-eureka: true
    fetch-registry: true

grpc:
  client:
    user-grpc-service:
      address: discovery:///${USER_DATABASE_SERVICE_APPLICATION_NAME}
      negotiation-type: plaintext

server:
  port: ${TRANSACTION_SERVICE_PORT}
