spring:
  application:
    name: service-discovery

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST}:${SERVICE_DISCOVERY_PORT}/eureka


server:
  port: ${SERVICE_DISCOVER_PORT}
