spring:
  application:
    name: ${SERVICE_DISCOVERY_APPLICATION_NAME}

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST}:${SERVICE_DISCOVERY_PORT}/eureka


server:
  port: ${SERVICE_DISCOVERY_PORT}
