spring:
  application:
    name: ${USER_DATABASE_SERVICE_APPLICATION_NAME}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_USER_HOST}:${POSTGRES_USER_PORT_INNER}/${POSTGRES_USER_DATABASE_NAME}
    username: ${POSTGRES_USER_USERNAME}
    password: ${POSTGRES_USER_PASSWORD}
  liquibase:
    change-log: db/changelog/main/main-changelog.yml
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST}:${SERVICE_DISCOVERY_PORT}/eureka
    register-with-eureka: true
    fetch-registry: true


server:
  port: ${USER_DATABASE_SERVICE_PORT}

grpc:
  server:
    port: ${USER_DATABASE_SERVICE_GRPC_PORT}
